version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      # 3 Baris ini akan mengikat file/folder fisik di VPS ke dalam container Docker
      - /opt/bot-wa-data/credentials.json:/var/www/html/storage/app/credentials.json
      - /opt/bot-wa-data/database.sqlite:/var/www/html/database/database.sqlite
      - /opt/bot-wa-data/bukti_tugas:/var/www/html/storage/app/public/bukti_tugas
    env_file:
      - .env
    depends_on:
      - wa-engine
    restart: always

  laravel-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan schedule:work
    volumes:
      - ./:/var/www/html
      - /opt/bot-wa-data/credentials.json:/var/www/html/storage/app/credentials.json
      - /opt/bot-wa-data/database.sqlite:/var/www/html/database/database.sqlite
    env_file:
      - .env
    depends_on:
      - laravel-app
    restart: always

  wa-engine:
    build:
      context: ./wa-engine
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./wa-engine:/app
      - /app/node_modules
    restart: always
