version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - /opt/bot-wa-data/.env:/var/www/html/.env
      - /opt/bot-wa-data/credentials.json:/var/www/html/storage/app/credentials.json
      - /opt/bot-wa-data/database.sqlite:/var/www/html/database/database.sqlite
      - /opt/bot-wa-data/bukti_tugas:/var/www/html/storage/app/public/bukti_tugas
    depends_on:
      - wa-engine
    restart: always

  laravel-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan schedule:work
    volumes:
      - /opt/bot-wa-data/.env:/var/www/html/.env
      - /opt/bot-wa-data/credentials.json:/var/www/html/storage/app/credentials.json
      - /opt/bot-wa-data/database.sqlite:/var/www/html/database/database.sqlite
    depends_on:
      - laravel-app
    restart: always

  wa-engine:
    build:
      context: ./wa-engine
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
